name: Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish to the GCloud Container Registry'
        required: true
        type: string

jobs:
  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Update version
        run: |
          poetry version $VERSION
          
          git config --global user.name "newspy"
          git config --global user.email "newspy@youremail.com"
          
          git add pyproject.toml
          git commit -m "chore: bump version to $VERSION"
          git push origin main

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
