name: Release

on:
  push:
    branches:
      - main

jobs:
  version:
    permissions:
      contents: write
      issues: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Update version
        run: |
          poetry version $(git describe --tags --abbrev=0)
          git add pyproject.toml
          git commit -m "chore: bump version to $(git describe --tags --abbrev=0)"
          git push origin main
